apiVersion: v1
kind: Pod
metadata:
  name: echo-server
  labels:
    app: echo-server
    tier: backend
spec:
  containers:
  - name: echo-server
    image: googlecontainer/echoserver:1.8
    ports:
      - containerPort: 8080
